name: trmultichat_mobile
description: TR Multichat Mobile (Flutter) - WhatsApp multiempresa
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State / Navigation
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1

  # Networking
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0

  # Realtime
  socket_io_client: ^2.0.3+1

  # Storage / Auth
  flutter_secure_storage: ^9.2.2

  # Media / Links
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  http_parser: ^4.0.2
  webview_flutter: ^4.8.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  crypto: ^3.0.3
  path: ^1.9.0

  # Notifications (local) - push-ready structure
  flutter_local_notifications: ^19.5.0

  # Utils / UI
  equatable: ^2.0.5
  local_auth: ^2.2.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icone-app.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
